name: iOS CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: actions/setup-xcode@v3
        with:
          xcode-version: '15.4'
          xcode-path: /Applications/Xcode_15.4.app

      - name: Install Dependencies (SPM)
        run: xcodebuild -resolvePackageDependencies

      - name: Build iOS App
        run: |
          xcodebuild clean build \
            -project iNotes.xcodeproj \
            -scheme iNotes \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=18.3.1" \
            CODE_SIGNING_ALLOWED=NO
